ALTER TABLE Categoria
ADD Estado BIT NOT NULL
CONSTRAINT Estatus_Categoria_Default DEFAULT 1 WITH VALUES;

ALTER TABLE Marca
ADD Estado BIT NOT NULL
CONSTRAINT Estatus_Marca_Default DEFAULT 1 WITH VALUES;