-- CREACIÓN DE TABLA COMPANIA V1.0
-- SCRIPT PUEDE EJECUTARSE MULTIPLES VECES EN LA BASE
-- CREA LA TABLA SI NO EXISTE CON TODOS LOS CAMPOS
-- SI YA EXISTE AGREGA O ACTUALIZA LOS CAMBIOS NECESARIOS
USE DB_141102_integraciond;
GO
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Companias')
BEGIN
    CREATE TABLE Companias (
        CompaniaId INT NOT NULL IDENTITY CONSTRAINT PK_Companias_CompaniaId PRIMARY KEY,
        Nombre NVARCHAR(100) NOT NULL,
        Descripcion NVARCHAR(100) NOT NULL,
        Direccion NVARCHAR(100) NOT NULL,
        Telefono NVARCHAR(40) NOT NULL,
        Email NVARCHAR(100) NOT NULL,
        Estado bit not null CONSTRAINT DF_Companias_Estado DEFAULT(1)
    );
END