-- CREACIÓN DE TABLA PRODUCTO_PROVEEDOR V1.0
-- SCRIPT PUEDE EJECUTARSE MULTIPLES VECES EN LA BASE
-- CREA LA TABLA SI NO EXISTE CON TODOS LOS CAMPOS
-- SI YA EXISTE AGREGA O ACTUALIZA LOS CAMBIOS NECESARIOS
USE DB_141102_integraciond;
GO
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Clientes')
BEGIN
    CREATE TABLE Clientes (
    ClienteId INT NOT NULL PRIMARY KEY IDENTITY,
    Nombres NVARCHAR(100) NOT NULL,
    Apellidos NVARCHAR(100) NOT NULL,
    Direccion NVARCHAR(100) NOT NULL,
    Telefono NVARCHAR(60) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Estado BIT NOT NULL
);

END